# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a3bb43839bb608b728085f2644eb97f6594f191797303c9996d16ad8b4b62f69eb5fde635dfc53641c550c71f32e884adeda78e86c1b7d71c29ef281ab13a78

test:
  secret_key_base: 8a5ec92a551a3b5d9248b1e5a4edfb7c4fd28ffd7f4550064f2956f6893391d017efdc54375f8774999de2bc426f0619fbae672d31279d65b0f0c5694dd1da21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
